# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c9ed0d331942f413fadc0c92492060f213c2cfba7a9114b59a49c3b74a77c4c8f47bd96fab35fa2ae6528bfc87c77d70bf38099c9a96c6cf6142eb37d7cb36a

test:
  secret_key_base: d9a4b4a910a635ac1e688c273f3297db83b5477130c5f3c1db20f41376488023e6093a4c761634fe9680f508c5efa2139a01773041ef3630c50cb64f10aa6a12

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
